### ISSUE TITLE
v0.8.4 build 7 - unable to login

### ISSUE THREAD

**Issue by abacao** [thanksmister/wallpanel-android-legacy#3]
I know this software is legacy and therefore the support may be no where to be found but here it goes:

I'm trying to run this on a very old tablet with 4.2.2.

I am able to install and run the application but when the homepage shows, I only have this:
![20200129_180534](https://user-images.githubusercontent.com/17479246/73383884-13b5ed80-42c2-11ea-9842-1df31b1d36ec.jpg)
and after clicking next I get this:
![20200129_180505](https://user-images.githubusercontent.com/17479246/73383921-26c8bd80-42c2-11ea-8085-67e384ae5f13.jpg)

Any help can be given?

**Comment by thanksmister** [comment]
I do not know what that HA message is about.  Possibly you cannot render the HA page code, like JavaScript, CSS, etc.  or you have some issue with your HA access.

**Comment by abacao** [comment]
Basicly I cannot see the form fields for username and password within the app. 
I can login with a browser in that same device.

This is the log file:
```
020-01-29 18:41:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 83, in handle_req
    resp = await func(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/auth/login_flow.py", line 234, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/auth/providers/homeassistant.py", line 287, in async_step_init
    user_input["username"], user_input["password"]
KeyError: 'username'
```

**Comment by thanksmister** [comment]
The application just renders the webpage in a WebView, you are not seeing the proper render page due to incompatibilities with the HTML/CSS/JS and the WebView or Crosswalk browser imbedded within the app. Again, this is not an issue I can fix.

**Comment by abacao** [comment]
I was just searching for help if someone was able to overcome this.

Can you please tell me what is the minimum android version for the latest app (the one not legacy)? 

Do you think it is possible to add fields to the username and password?

**Comment by abacao** [comment]
I have found a possible solution (little hack)
```
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
    - type: homeassistant
```

1. Use this code and login with the app.
2. Save the login
3. Comment the code above
4. Profit
